# Generated by Django 5.0.6 on 2026-05-16 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEquipementSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_equipement', models.CharField(db_index=True, help_text='Ex: pc, switch, camera_ip, nas, onduleur…', max_length=50, verbose_name="Type d'équipement")),
                ('champ', models.CharField(help_text='Ex: ram_go, nb_ports, resolution_mp', max_length=60, verbose_name='Nom du champ (clé JSONB)')),
                ('label', models.CharField(help_text='Ex: RAM (Go), Nombre de ports', max_length=100, verbose_name='Label affiché')),
                ('type_donnee', models.CharField(choices=[('string', 'Texte'), ('integer', 'Entier'), ('float', 'Décimal'), ('boolean', 'Booléen'), ('ip', 'Adresse IP'), ('mac', 'Adresse MAC'), ('date', 'Date')], default='string', max_length=10, verbose_name='Type de donnée')),
                ('obligatoire', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('unite', models.CharField(blank=True, help_text='Ex: Go, MHz, W, MP', max_length=20, verbose_name='Unité')),
                ('valeur_defaut', models.CharField(blank=True, max_length=200, verbose_name='Valeur par défaut')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Schéma de type d'équipement",
                'verbose_name_plural': "Schémas de types d'équipement",
                'db_table': 'type_equipement_schema',
                'ordering': ['type_equipement', 'ordre_affichage', 'champ'],
                'unique_together': {('type_equipement', 'champ')},
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_inventaire', models.CharField(help_text='Ex: INF-2026-0142', max_length=50, unique=True, verbose_name='Tag inventaire')),
                ('type_equipement', models.CharField(db_index=True, max_length=50, verbose_name="Type d'équipement")),
                ('nom', models.CharField(max_length=150, verbose_name='Nom / désignation')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(blank=True, max_length=150, verbose_name='Modèle')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numéro de série')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('stock', 'En stock'), ('maintenance', 'En maintenance'), ('reforme', 'Réformé')], db_index=True, default='actif', max_length=20, verbose_name='Statut')),
                ('localisation', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('service', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Service')),
                ('date_acquisition', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('cout_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Coût d'achat (FCFA)")),
                ('fin_garantie', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fin de garantie')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('attributs_specifiques', models.JSONField(blank=True, default=dict, help_text='Champs propres au type, définis dans TypeEquipementSchema.', verbose_name='Attributs spécifiques')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('technicien_referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_geres', to=settings.AUTH_USER_MODEL, verbose_name='Technicien référent')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_affectes', to=settings.AUTH_USER_MODEL, verbose_name='Affecté à')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'db_table': 'equipements',
                'ordering': ['tag_inventaire'],
                'indexes': [models.Index(fields=['attributs_specifiques'], name='idx_equip_attrs_gin')],
            },
        ),
    ]
