# Generated by Django 5.0.6 on 2026-05-18 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du logiciel')),
                ('editeur', models.CharField(blank=True, max_length=150, verbose_name='Éditeur')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version de référence')),
                ('type_licence', models.CharField(choices=[('perpetuelle', 'Perpétuelle'), ('abonnement', 'Abonnement'), ('volume', 'Volume'), ('open_source', 'Open source'), ('gratuit', 'Gratuit')], default='perpetuelle', max_length=20, verbose_name='Type de licence')),
                ('nb_postes_autorises', models.PositiveIntegerField(blank=True, help_text='Laisser vide si illimité', null=True, verbose_name='Nb postes autorisés')),
                ('cout_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Coût annuel (FCFA)')),
                ('date_achat', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('date_expiration', models.DateField(blank=True, help_text='Laisser vide si perpétuelle', null=True, verbose_name="Date d'expiration")),
                ('alerte_active', models.BooleanField(default=True, verbose_name='Alerte renouvellement')),
                ('jours_alerte', models.PositiveSmallIntegerField(default=30, help_text='Alerte envoyée X jours avant expiration', verbose_name='Délai alerte (jours)')),
                ('cle_licence', models.CharField(blank=True, help_text='Stockée en clair — envisager un coffre-fort pour la prod', max_length=255, verbose_name='Clé de licence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logiciel',
                'verbose_name_plural': 'Logiciels',
                'db_table': 'logiciels',
                'ordering': ['nom', 'editeur'],
            },
        ),
        migrations.CreateModel(
            name='InstallationLogiciel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_installee', models.CharField(blank=True, max_length=50, verbose_name='Version installée')),
                ('date_installation', models.DateField(verbose_name="Date d'installation")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logiciels_installes', to='equipements.equipement', verbose_name='Équipement')),
                ('installe_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Installé par')),
                ('logiciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='equipements.logiciel', verbose_name='Logiciel')),
            ],
            options={
                'verbose_name': 'Installation logiciel',
                'verbose_name_plural': 'Installations logiciel',
                'db_table': 'installations_logiciel',
                'ordering': ['-date_installation'],
                'unique_together': {('logiciel', 'equipement')},
            },
        ),
    ]
