# Generated by Django 5.0.6 on 2026-05-16 13:06

import apps.tickets.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priorite', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], max_length=20, unique=True)),
                ('delai_prise_charge', models.PositiveIntegerField(help_text='Délai de prise en charge (minutes)')),
                ('delai_resolution', models.PositiveIntegerField(help_text='Délai de résolution (minutes)')),
                ('heures_ouvrables', models.BooleanField(default=True, help_text='Calcul sur heures ouvrables uniquement')),
                ('heure_debut', models.TimeField(default='08:00', help_text='Début des heures ouvrables')),
                ('heure_fin', models.TimeField(default='18:00', help_text='Fin des heures ouvrables')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration SLA',
            },
        ),
        migrations.CreateModel(
            name='CategorieTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type_ticket', models.CharField(blank=True, choices=[('incident', 'Incident'), ('demande', 'Demande de service'), ('changement', 'Changement'), ('probleme', 'Problème')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='tickets.categorieticket')),
            ],
            options={
                'verbose_name': 'Catégorie de ticket',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('interne', models.BooleanField(default=False, help_text='Note interne visible uniquement par les techniciens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_ticket', models.CharField(choices=[('incident', 'Incident'), ('demande', 'Demande de service'), ('changement', 'Changement'), ('probleme', 'Problème')], default='incident', max_length=20)),
                ('priorite', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('assigne', 'Assigné'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('resolu', 'Résolu'), ('ferme', 'Fermé'), ('annule', 'Annulé')], default='nouveau', max_length=20)),
                ('echeance_prise_charge', models.DateTimeField(blank=True, null=True)),
                ('echeance_resolution', models.DateTimeField(blank=True, null=True)),
                ('pris_en_charge_le', models.DateTimeField(blank=True, null=True)),
                ('resolu_le', models.DateTimeField(blank=True, null=True)),
                ('ferme_le', models.DateTimeField(blank=True, null=True)),
                ('solution', models.TextField(blank=True)),
                ('satisfaction', models.PositiveSmallIntegerField(blank=True, help_text='Note de satisfaction 1-5', null=True)),
                ('commentaire_cloture', models.TextField(blank=True)),
                ('escalade', models.BooleanField(default=False)),
                ('escalade_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.categorieticket')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_demandes', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='equipements.equipement')),
                ('escalade_vers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_escalades', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_tickets', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to=apps.tickets.models.attachment_upload_path)),
                ('nom_original', models.CharField(max_length=255)),
                ('taille', models.PositiveIntegerField(help_text='Taille en octets')),
                ('mime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_jointes', to='tickets.commentaire')),
                ('uploade_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notif', models.CharField(choices=[('ticket_cree', 'Nouveau ticket créé'), ('ticket_assigne', 'Ticket assigné'), ('ticket_commente', 'Nouveau commentaire'), ('ticket_resolu', 'Ticket résolu'), ('ticket_ferme', 'Ticket fermé'), ('sla_depassement', 'Dépassement SLA'), ('sla_avertissement', 'Avertissement SLA (80%)'), ('escalade', 'Ticket escaladé')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('email_envoye', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.PositiveIntegerField(blank=True, help_text='Calculé automatiquement si début + fin fournis', null=True)),
                ('sur_site', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('champ_modifie', models.CharField(max_length=100)),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commentaire',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='tickets.ticket'),
        ),
        migrations.CreateModel(
            name='ArticleBaseConnaissances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('publie', models.BooleanField(default=False)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('utile_oui', models.PositiveIntegerField(default=0)),
                ('utile_non', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='tickets.categorieticket')),
                ('ticket_source', models.ForeignKey(blank=True, help_text="Ticket à l'origine de cet article", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_kb', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Article base de connaissances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['statut'], name='tickets_tic_statut_d111b2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priorite'], name='tickets_tic_priorit_ccbe02_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigne_a', 'statut'], name='tickets_tic_assigne_4ab9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['demandeur'], name='tickets_tic_demande_4a97a0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['echeance_resolution'], name='tickets_tic_echeanc_38df35_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', 'lue'], name='tickets_not_destina_3597be_idx'),
        ),
        migrations.AddIndex(
            model_name='articlebaseconnaissances',
            index=models.Index(fields=['publie'], name='tickets_art_publie_a33786_idx'),
        ),
    ]
