# Generated by Django 5.0.6 on 2026-06-06 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom du service')),
                ('code', models.CharField(blank=True, help_text='Ex: DSI, DRH, DAF — généré automatiquement si vide', max_length=20, unique=True, verbose_name='Code court')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('localisation', models.CharField(blank=True, help_text='Bâtiment, étage, aile…', max_length=200, verbose_name='Localisation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_geres', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['nom'],
            },
        ),
    ]
